FROM maven:3.9.6-eclipse-temurin-17-alpine AS build
WORKDIR /app

RUN apk add --no-cache gcompat

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

RUN adduser -D app_user \
    && chown -R app_user:app_user /app \
    && chmod 500 app.jar

USER app_user

EXPOSE 8080
EXPOSE 9090

ENTRYPOINT ["java", "-jar", "app.jar"]