spring.application.name=ms-unidade

spring.datasource.url=jdbc:postgresql://localhost:5432/unidade
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

grpc.server.port=9090

server.port=8080